# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(default='action', max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=id)),
                ('is_enable', models.BooleanField(default=True)),
                ('action_order', models.IntegerField()),
                ('templatesource', models.CharField(default='personnel/index.html', max_length=250)),
                ('query_function', models.CharField(default='GetIndex', max_length=20)),
            ],
            options={
                'ordering': ('menu_id', 'action_order'),
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('leader_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('leader_id',),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('menu_parent', models.CharField(default='000000', max_length=6)),
                ('menu_type', models.CharField(choices=[('g', 'Group'), ('p', 'Page')], default='g', max_length=1)),
                ('menu_name', models.CharField(default='menu', max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=models.CharField(max_length=6, primary_key=True, serialize=False))),
                ('is_active', models.BooleanField(default=True)),
                ('menu_order', models.IntegerField()),
                ('templatesource', models.CharField(default='personalia/index.html', max_length=250)),
                ('query_function', models.CharField(default='GetIndex', max_length=20)),
            ],
            options={
                'ordering': ('menu_parent', 'menu_order'),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthplace', models.CharField(max_length=15)),
                ('birth', models.DateField()),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1)),
                ('address', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('1', 'Lajang'), ('2', 'Menikah'), ('3', 'Janda/Duda')], default='1', max_length=1)),
                ('school', models.CharField(max_length=50)),
                ('graduate', models.CharField(choices=[('1', 'SD'), ('2', 'SMP'), ('3', 'SMA'), ('4', 'D3'), ('5', 'S1')], default='1', max_length=3)),
                ('mobilephone', models.CharField(max_length=15)),
                ('bbm', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'ordering': ('gender', 'name', 'birth'),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personalia.Person')),
                ('grade', models.CharField(choices=[('0', 'Calon Karyawan'), ('1', 'Pra A1'), ('2', 'A1'), ('3', 'A2')], default='1', max_length=1)),
                ('date_register', models.DateField(blank=True, null=True)),
                ('status_active', models.CharField(choices=[('c', 'Calon'), ('a', 'Active'), ('p', 'Passive')], default='a', max_length=1)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LeaderOf', to='personalia.Leader')),
            ],
            options={
                'ordering': ('status_active', 'grade', 'person'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('name', 'birth', 'gender', 'email')]),
        ),
        migrations.AddField(
            model_name='action',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionMenu', to='personalia.Menu'),
        ),
    ]
