# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=200)),
                ('script_name', models.CharField(max_length=200)),
                ('group_report', models.CharField(max_length=10)),
                ('is_enable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('report_name',),
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.CharField(choices=[('0', 'Kandidat'), ('1', 'Pra A1'), ('2', 'A1'), ('3', 'A2')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status_active',
            field=models.CharField(choices=[('a', 'Active'), ('p', 'Passive')], default='a', max_length=1),
        ),
    ]
