# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalia', '0002_auto_20170412_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_header',
            field=models.CharField(default='action', max_length=250),
        ),
    ]
