# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalia', '0003_action_action_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_direct',
            field=models.BooleanField(default=True),
        ),
    ]
