# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalia', '0004_action_is_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_act_view',
            field=models.BooleanField(default=True),
        ),
    ]
