# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personalia', '0005_menu_is_act_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('date_coaching', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empOf', to='personalia.Employee')),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='templatesource',
            field=models.CharField(default='personalia/index.html', max_length=250),
        ),
    ]
