# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalia', '0006_auto_20170415_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coaching',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ('manager', 'leader_id')},
        ),
        migrations.AddField(
            model_name='leader',
            name='manager',
            field=models.CharField(choices=[('ahm', 'ahmad'), ('ksm', 'kusmawan'), ('mgd', 'migud'), ('sdk', 'sodikin'), ('sdr', 'sodirun')], default='sdk', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.CharField(choices=[('0', 'WB'), ('1', 'Pra A1'), ('2', 'A1_1'), ('3', 'A1_2'), ('4', 'A1_3'), ('5', 'A2_a'), ('6', 'A2_b')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status_active',
            field=models.CharField(choices=[('ak', 'AK'), ('pa', 'PA'), ('bk1', 'BK_1'), ('bk2', 'BK_2'), ('bk3', 'BK_3')], max_length=1),
        ),
    ]
