# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalia', '0007_auto_20170425_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bbm',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
