# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalia', '0008_auto_20170425_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status_active',
            field=models.CharField(choices=[('ak', 'AK'), ('pa', 'PA'), ('bk1', 'BK_1'), ('bk2', 'BK_2'), ('bk3', 'BK_3')], max_length=5),
        ),
    ]
