# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='templatesource',
            field=models.CharField(default='training/index.html', max_length=250),
        ),
        migrations.AlterField(
            model_name='menu',
            name='templatesource',
            field=models.CharField(default='training/index.html', max_length=250),
        ),
    ]
