# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_entrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='date_input',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
